---
name: Build and Test

env:
  GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}

on:
  workflow_dispatch:
  push:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Setup SSH Agent
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
#
#      - name: Clone Required Repos
#        run: git clone git@github.com:TetraVeda/kaslcred.git

      - name: Resolve Version
        run: |
          IMAGE_VERSION=$(git describe --tags --abbrev=0)
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "building version $IMAGE_VERSION"

      - name: Install dependencies
        run: PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
          
      - name: Run tests
        run: python -m pytest

      - name: Build
        run: python -m build